reauthenticate works with token
userwidgets/api pull request #65
Opened 2023-10-06 07:44 UTC by linusarnejohansson

2023-10-06 07:52 UTC, EliasEriksson requested changes

2023-10-06 07:52 UTC, EliasEriksson commented on Context/Users/index.ts
> +		return await this.user("email" in credentials ? credentials.email : credentials.user).post<userwidgets.User>( //should work
remove comment

2023-10-06 08:05 UTC, TheLillyleaf requested changes
Small things

2023-10-06 08:37 UTC, TheLillyleaf approved these changes

2023-10-09 07:17 UTC, EliasEriksson approved these changes

2023-10-09 07:17 UTC, merged